### ISSUE TITLE
【bug报告】前端展示bug

### ISSUE THREAD

**Issue by jack-luj** [sunlightcs/renren-security#2]
![image](https://cloud.githubusercontent.com/assets/13581261/23338219/9326368c-fc3f-11e6-96eb-fb45faf9b95a.png)

如图，使用源码maven方式运行，原数据，打开菜单管理，对定时任务的修改菜单进行编辑时，在打开的编辑界面出现的上级菜单为以及菜单，应当为定时任务，偶尔出现此情况，并不局限于此菜单，怀疑为前端展示bug，使用chrome 56.0.2924.87

**Comment by xiaozhou010** [comment]
这个很可能是异步加载出现了问题,建议多次请求依次按顺序请求,把回显放到最后的一次请求去处理

**Comment by jack-luj** [comment]
按照 @xiaozhou010  的建议修改已经奏效，tks!
